// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.2.0
// source: message.proto

package message

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PortMapping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostPort      string                 `protobuf:"bytes,1,opt,name=host_port,json=hostPort,proto3" json:"host_port,omitempty"`
	ContainerPort string                 `protobuf:"bytes,2,opt,name=container_port,json=containerPort,proto3" json:"container_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortMapping) Reset() {
	*x = PortMapping{}
	mi := &file_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortMapping) ProtoMessage() {}

func (x *PortMapping) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortMapping.ProtoReflect.Descriptor instead.
func (*PortMapping) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *PortMapping) GetHostPort() string {
	if x != nil {
		return x.HostPort
	}
	return ""
}

func (x *PortMapping) GetContainerPort() string {
	if x != nil {
		return x.ContainerPort
	}
	return ""
}

type ResourceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemRequired   uint64                 `protobuf:"varint,1,opt,name=mem_required,json=memRequired,proto3" json:"mem_required,omitempty"`
	DiskRequired  uint64                 `protobuf:"varint,2,opt,name=disk_required,json=diskRequired,proto3" json:"disk_required,omitempty"`
	CpuRequired   int32                  `protobuf:"varint,3,opt,name=cpu_required,json=cpuRequired,proto3" json:"cpu_required,omitempty"`
	TargetPort    []*PortMapping         `protobuf:"bytes,4,rep,name=target_port,json=targetPort,proto3" json:"target_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceReq) Reset() {
	*x = ResourceReq{}
	mi := &file_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceReq) ProtoMessage() {}

func (x *ResourceReq) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceReq.ProtoReflect.Descriptor instead.
func (*ResourceReq) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceReq) GetMemRequired() uint64 {
	if x != nil {
		return x.MemRequired
	}
	return 0
}

func (x *ResourceReq) GetDiskRequired() uint64 {
	if x != nil {
		return x.DiskRequired
	}
	return 0
}

func (x *ResourceReq) GetCpuRequired() int32 {
	if x != nil {
		return x.CpuRequired
	}
	return 0
}

func (x *ResourceReq) GetTargetPort() []*PortMapping {
	if x != nil {
		return x.TargetPort
	}
	return nil
}

type ResourceRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Done          bool                   `protobuf:"varint,1,opt,name=done,proto3" json:"done,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceRes) Reset() {
	*x = ResourceRes{}
	mi := &file_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRes) ProtoMessage() {}

func (x *ResourceRes) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRes.ProtoReflect.Descriptor instead.
func (*ResourceRes) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{2}
}

func (x *ResourceRes) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *ResourceRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ContainerId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerId) Reset() {
	*x = ContainerId{}
	mi := &file_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerId) ProtoMessage() {}

func (x *ContainerId) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerId.ProtoReflect.Descriptor instead.
func (*ContainerId) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{3}
}

func (x *ContainerId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ContainerIds struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []string               `protobuf:"bytes,1,rep,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerIds) Reset() {
	*x = ContainerIds{}
	mi := &file_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerIds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerIds) ProtoMessage() {}

func (x *ContainerIds) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerIds.ProtoReflect.Descriptor instead.
func (*ContainerIds) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{4}
}

func (x *ContainerIds) GetId() []string {
	if x != nil {
		return x.Id
	}
	return nil
}

type Port struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PortIP        string                 `protobuf:"bytes,1,opt,name=portIP,proto3" json:"portIP,omitempty"`
	PrivatePort   string                 `protobuf:"bytes,2,opt,name=privatePort,proto3" json:"privatePort,omitempty"`
	PublicPort    string                 `protobuf:"bytes,3,opt,name=publicPort,proto3" json:"publicPort,omitempty"`
	PortType      string                 `protobuf:"bytes,4,opt,name=portType,proto3" json:"portType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Port) Reset() {
	*x = Port{}
	mi := &file_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Port) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Port) ProtoMessage() {}

func (x *Port) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Port.ProtoReflect.Descriptor instead.
func (*Port) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{5}
}

func (x *Port) GetPortIP() string {
	if x != nil {
		return x.PortIP
	}
	return ""
}

func (x *Port) GetPrivatePort() string {
	if x != nil {
		return x.PrivatePort
	}
	return ""
}

func (x *Port) GetPublicPort() string {
	if x != nil {
		return x.PublicPort
	}
	return ""
}

func (x *Port) GetPortType() string {
	if x != nil {
		return x.PortType
	}
	return ""
}

type ContainerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=containerId,proto3" json:"containerId,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Image         string                 `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	ImageId       string                 `protobuf:"bytes,5,opt,name=imageId,proto3" json:"imageId,omitempty"`
	Ports         []string               `protobuf:"bytes,6,rep,name=ports,proto3" json:"ports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerInfo) Reset() {
	*x = ContainerInfo{}
	mi := &file_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerInfo) ProtoMessage() {}

func (x *ContainerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerInfo.ProtoReflect.Descriptor instead.
func (*ContainerInfo) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{6}
}

func (x *ContainerInfo) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ContainerInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ContainerInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ContainerInfo) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ContainerInfo) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *ContainerInfo) GetPorts() []string {
	if x != nil {
		return x.Ports
	}
	return nil
}

type ContainerInfoRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Containers    []*ContainerInfo       `protobuf:"bytes,1,rep,name=Containers,proto3" json:"Containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerInfoRes) Reset() {
	*x = ContainerInfoRes{}
	mi := &file_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerInfoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerInfoRes) ProtoMessage() {}

func (x *ContainerInfoRes) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerInfoRes.ProtoReflect.Descriptor instead.
func (*ContainerInfoRes) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{7}
}

func (x *ContainerInfoRes) GetContainers() []*ContainerInfo {
	if x != nil {
		return x.Containers
	}
	return nil
}

type ContainerStatsRes struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ContainerStats string                 `protobuf:"bytes,1,opt,name=containerStats,proto3" json:"containerStats,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ContainerStatsRes) Reset() {
	*x = ContainerStatsRes{}
	mi := &file_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerStatsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerStatsRes) ProtoMessage() {}

func (x *ContainerStatsRes) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerStatsRes.ProtoReflect.Descriptor instead.
func (*ContainerStatsRes) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{8}
}

func (x *ContainerStatsRes) GetContainerStats() string {
	if x != nil {
		return x.ContainerStats
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{9}
}

var File_message_proto protoreflect.FileDescriptor

const file_message_proto_rawDesc = "" +
	"\n" +
	"\rmessage.proto\x1a\x1cgoogle/api/annotations.proto\"Q\n" +
	"\vPortMapping\x12\x1b\n" +
	"\thost_port\x18\x01 \x01(\tR\bhostPort\x12%\n" +
	"\x0econtainer_port\x18\x02 \x01(\tR\rcontainerPort\"\xa7\x01\n" +
	"\vResourceReq\x12!\n" +
	"\fmem_required\x18\x01 \x01(\x04R\vmemRequired\x12#\n" +
	"\rdisk_required\x18\x02 \x01(\x04R\fdiskRequired\x12!\n" +
	"\fcpu_required\x18\x03 \x01(\x05R\vcpuRequired\x12-\n" +
	"\vtarget_port\x18\x04 \x03(\v2\f.PortMappingR\n" +
	"targetPort\";\n" +
	"\vResourceRes\x12\x12\n" +
	"\x04done\x18\x01 \x01(\bR\x04done\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x1d\n" +
	"\vContainerId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1e\n" +
	"\fContainerIds\x12\x0e\n" +
	"\x02id\x18\x01 \x03(\tR\x02id\"|\n" +
	"\x04Port\x12\x16\n" +
	"\x06portIP\x18\x01 \x01(\tR\x06portIP\x12 \n" +
	"\vprivatePort\x18\x02 \x01(\tR\vprivatePort\x12\x1e\n" +
	"\n" +
	"publicPort\x18\x03 \x01(\tR\n" +
	"publicPort\x12\x1a\n" +
	"\bportType\x18\x04 \x01(\tR\bportType\"\xa5\x01\n" +
	"\rContainerInfo\x12 \n" +
	"\vcontainerId\x18\x01 \x01(\tR\vcontainerId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x14\n" +
	"\x05image\x18\x04 \x01(\tR\x05image\x12\x18\n" +
	"\aimageId\x18\x05 \x01(\tR\aimageId\x12\x14\n" +
	"\x05ports\x18\x06 \x03(\tR\x05ports\"B\n" +
	"\x10ContainerInfoRes\x12.\n" +
	"\n" +
	"Containers\x18\x01 \x03(\v2\x0e.ContainerInfoR\n" +
	"Containers\";\n" +
	"\x11ContainerStatsRes\x12&\n" +
	"\x0econtainerStats\x18\x01 \x01(\tR\x0econtainerStats\"\a\n" +
	"\x05Empty2\xc8\x02\n" +
	"\x0fResourceService\x12G\n" +
	"\x10AllocateResource\x12\f.ResourceReq\x1a\f.ResourceRes\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/resource\x12P\n" +
	"\x17DeleteAllocatedResource\x12\f.ContainerId\x1a\f.ResourceRes\"\x19\x82\xd3\xe4\x93\x02\x13*\x11/v1/resource/{id}\x12H\n" +
	"\x15GetAllocatedResources\x12\x06.Empty\x1a\x11.ContainerInfoRes\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/resource\x12P\n" +
	"\x11GetContainerStats\x12\f.ContainerId\x1a\x12.ContainerStatsRes\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/resource/{id}BJZH./proto-gen/github.com/chahatsagarmain/OnDemandCompute/proto-gen/messageb\x06proto3"

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData []byte
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)))
	})
	return file_message_proto_rawDescData
}

var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_message_proto_goTypes = []any{
	(*PortMapping)(nil),       // 0: PortMapping
	(*ResourceReq)(nil),       // 1: ResourceReq
	(*ResourceRes)(nil),       // 2: ResourceRes
	(*ContainerId)(nil),       // 3: ContainerId
	(*ContainerIds)(nil),      // 4: ContainerIds
	(*Port)(nil),              // 5: Port
	(*ContainerInfo)(nil),     // 6: ContainerInfo
	(*ContainerInfoRes)(nil),  // 7: ContainerInfoRes
	(*ContainerStatsRes)(nil), // 8: ContainerStatsRes
	(*Empty)(nil),             // 9: Empty
}
var file_message_proto_depIdxs = []int32{
	0, // 0: ResourceReq.target_port:type_name -> PortMapping
	6, // 1: ContainerInfoRes.Containers:type_name -> ContainerInfo
	1, // 2: ResourceService.AllocateResource:input_type -> ResourceReq
	3, // 3: ResourceService.DeleteAllocatedResource:input_type -> ContainerId
	9, // 4: ResourceService.GetAllocatedResources:input_type -> Empty
	3, // 5: ResourceService.GetContainerStats:input_type -> ContainerId
	2, // 6: ResourceService.AllocateResource:output_type -> ResourceRes
	2, // 7: ResourceService.DeleteAllocatedResource:output_type -> ResourceRes
	7, // 8: ResourceService.GetAllocatedResources:output_type -> ContainerInfoRes
	8, // 9: ResourceService.GetContainerStats:output_type -> ContainerStatsRes
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
